CALL 0 initVars 0
STR | II CONTEXTHEAD 2 0
STR | II STACKEND 2 0


JMP | EQ | II 0 0 main



#
# Begin definition of fibb
#

# returnVarOffset is always 0

label fibb_
# Load value of N into REG0
LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 NOffset REG0
LOAD | RR REG0 REG0 0

# Test in N equals 1 or 0
JMP | EQ | RI REG0 0 zero
JMP | EQ | RI REG0 1 one

# A=fibb(N-1)

#
# Begin fibb call
#

# Store N in REG5 IMPORTANT FOR LATER
LOAD | IR CONTEXTHEAD REG0 0
ADD | II NOffset 0 REG0
LOAD | RR REG0 REG5 0

# Allocates RAM for returnVar
# Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Save CONTEXTHEAD and move it forward
LOAD | IR CONTEXTHEAD REG0 0
PUSH | RR 0 REG0 0
LOAD | IR STACKEND REG0 0
STR | IR CONTEXTHEAD REG0 0

# Save STACKEND
LOAD | IR STACKEND REG0 0
PUSH | RR 0 REG0 0

# Allocates RAM for N
#Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Store N-1 into N    N STORED IN REG5 FROM EARLIER
LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 NOffset REG0
SUB | RI REG5 1 REG1
STR | RR REG0 REG1 0

CALL 0 fibb 0

# Restore STACKEND and CONTEXTHEAD
POP | RR 0 REG0 0
STR | IR STACKEND REG0 0
POP | RR 0 REG0 0
STR | IR CONTEXTHEAD REG0 0

#
# end fibb call
#

# B=fibb(N-2)

#
# Begin fibb call
#

# Store N in REG5 IMPORTANT FOR LATER
LOAD | IR CONTEXTHEAD REG0 0
ADD | II NOffset 0 REG0
LOAD | RR REG0 REG5 0

# Allocates RAM for returnVar
# Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Save CONTEXTHEAD and move it forward
LOAD | IR CONTEXTHEAD REG0 0
PUSH | RR 0 REG0 0
LOAD | IR STACKEND REG0 0
STR | IR CONTEXTHEAD REG0 0

# Save STACKEND
LOAD | IR STACKEND REG0 0
PUSH | RR 0 REG0 0

# Allocates RAM for N
#Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Store N-2 into N    N STORED IN REG5 FROM EARLIER
LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 NOffset REG0
SUB | RI REG5 2 REG1
STR | RR REG0 REG1 0

CALL 0 fibb 0

# Restore STACKEND and CONTEXTHEAD
POP | RR 0 REG0 0
STR | IR STACKEND REG0 0
POP | RR 0 REG0 0
STR | IR CONTEXTHEAD REG0 0

#
# end fibb call
#

LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 0 REG1
ADD | RI REG0 AOffset REG0
ADD | RI REG1 BOffset REG1
LOAD | RR REG0 REG0 0
LOAD | RR REG1 REG1 0
ADD | RR REG0 REG1 REG0
LOAD | IR CONTEXTHEAD REG1 0
STR | RR REG1 REG0 0

RET 0 0 COUNTER

label zero_
LOAD | IR CONTEXTHEAD REG0 0
STR | RI REG0 0 0
RET 0 0 COUNTER

label one_
LOAD | IR CONTEXTHEAD REG0 0
STR | RI REG0 1 0
RET 0 0 COUNTER

#
# End definition of fibb
#



#
# MAIN
#

label main_

#
# Begin fibb call
#

# Allocates RAM for returnVar
# Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Save CONTEXTHEAD and move it forward
LOAD | IR CONTEXTHEAD REG0 0
PUSH | RR 0 REG0 0
LOAD | IR STACKEND REG0 0
STR | IR CONTEXTHEAD REG0 0

# Save STACKEND
LOAD | IR STACKEND REG0 0
PUSH | RR 0 REG0 0

# Allocates RAM for N
#Increment STACKEND
LOAD | IR STACKEND REG0 0
ADD | RI REG0 1 REG0
STR | IR STACKEND REG0 0

# Store numFibbs into N
LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 NOffset REG0
STR | RI REG0 numFibbs 0

CALL 0 fibb 0

# Restore STACKEND and CONTEXTHEAD
POP | RR 0 REG0 0
STR | IR STACKEND REG0 0
POP | RR 0 REG0 0
STR | IR CONTEXTHEAD REG0 0

#
# end fibb call
#

# Store return value into REG0 so I can see it
LOAD | IR CONTEXTHEAD REG0 0
ADD | RI REG0 returnVarOffset REG0
LOAD | RR REG0 REG0 0

label infiniteLoop_
JMP | EQ | II 0 0 infiniteLoop

# Initialize variables
label initVars_
RET 0 0 COUNTER

# consts:
const CONTEXTHEAD 0
const STACKEND 1
const numFibbs 3
const NOffset 1
const fibb 4
const AOffset NOffset+1
const BOffset AOffset+1
const zero 67
const one 70
const main 73
const returnVarOffset 0
const infiniteLoop 96
const initVars 97

